module.exports = {
  apps: [
    {
      name: "whatsapp-bridge",
      script: "dist/index.js",
      cwd: "/Users/joel/Projects/Nanobot/bridge",
      interpreter: "node",
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
    },
    {
      name: "nanobot-api",
      script: "/Users/joel/Projects/Nanobot/start-api.py",
      interpreter: "/Users/joel/Projects/Nanobot/.venv/bin/python",
      cwd: "/Users/joel/Projects/Nanobot",
      env: {
        GROQ_API_KEY: process.env.GROQ_API_KEY || "",
        NANOBOT_TOOLS__POSTIZ__ENABLED: "true",
        NANOBOT_TOOLS__POSTIZ__BASE_URL: "http://localhost:4007",
        NANOBOT_TOOLS__POSTIZ__API_KEY: "b0cdba1a151dba58aaa9055368a9e8a96b98e857a6e78513d848a6de6d77a9ea",
        NANOBOT_TOOLS__POSTIZ__API_KEY_PREFIX: "",
        NANOBOT_TOOLS__POSTIZ__PUBLISH_PATH: "/api/public/v1/posts",
        NANOBOT_TOOLS__POSTIZ__DEFAULT_INTEGRATION_ID: "cmius86vx0005mg83ye5lei7a",
      },
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
    },
    {
      name: "paperclip",
      script: "/Users/joel/.npm/_npx/43414d9b790239bb/node_modules/.bin/paperclipai",
      args: "run",
      cwd: "/Users/joel/Projects/Nanobot",
      interpreter: "node",
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
    },
    {
      name: "paperclip-relay",
      script: "src/paperclip-relay.ts",
      cwd: "/Users/joel/Projects/Nanobot/bridge",
      interpreter: "/Users/joel/Projects/Nanobot/bridge/node_modules/.bin/tsx",
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
    },
  ],
};
