-- Street Gallery sample artworks seed
-- Idempotent — run anytime against an existing social DB. Safe to re-run.
-- Usage:
--   docker exec -i nanobot-social-postgres psql -U social -d social < deploy/seeds/gallery-samples.sql
-- Or via the wrapper: bash deploy/seeds/seed-gallery.sh

BEGIN;

INSERT INTO gallery_artworks (id, artist_name, title, description, medium, style, year_created, image_url, is_featured, is_public, display_order, is_for_sale, price, currency, accepts_commissions, tags, view_count, favorite_count, comment_count, share_count, is_approved, created_at, updated_at) VALUES ('ga-001', 'Maria Reyes', 'Urban Pulse', 'A vibrant depiction of city life through abstract lens', 'Digital Art', 'Abstract', '2025', 'https://picsum.photos/seed/ga001/800/600', 't', 't', '1', 't', '450.00', 'CAD', 'f', '{abstract,colorful,urban,digital}', '234', '19', '0', '0', 't', '2026-03-27 15:08:30.146', '2026-03-27 15:08:30.146') ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery_artworks (id, artist_name, title, description, medium, style, year_created, image_url, is_featured, is_public, display_order, is_for_sale, price, currency, accepts_commissions, tags, view_count, favorite_count, comment_count, share_count, is_approved, created_at, updated_at) VALUES ('ga-002', 'Jamal Carter', 'Concrete Dreams', 'Street art meets fine art in this mixed media piece', 'Mixed Media', 'Contemporary', '2024', 'https://picsum.photos/seed/ga002/800/600', 't', 't', '2', 't', '1200.00', 'CAD', 'f', '{street,mixed-media,contemporary,bold}', '567', '42', '0', '0', 't', '2026-03-27 15:08:30.146', '2026-03-27 15:08:30.146') ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery_artworks (id, artist_name, title, description, medium, style, year_created, image_url, is_featured, is_public, display_order, is_for_sale, price, currency, accepts_commissions, tags, view_count, favorite_count, comment_count, share_count, is_approved, created_at, updated_at) VALUES ('ga-003', 'Yuki Tanaka', 'Neon Reflections', 'Cyberpunk inspired digital painting of Tokyo streets', 'Digital Art', 'Cyberpunk', '2026', 'https://picsum.photos/seed/ga003/800/600', 'f', 't', '3', 't', '800.00', 'CAD', 'f', '{cyberpunk,neon,tokyo,night}', '189', '16', '0', '0', 't', '2026-03-27 15:08:30.146', '2026-03-27 15:08:30.146') ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery_artworks (id, artist_name, title, description, medium, style, year_created, image_url, is_featured, is_public, display_order, is_for_sale, price, currency, accepts_commissions, tags, view_count, favorite_count, comment_count, share_count, is_approved, created_at, updated_at) VALUES ('ga-004', 'Elena Dubois', 'Morning Light', 'Watercolor study of light filtering through autumn leaves', 'Watercolor', 'Impressionism', '2025', 'https://picsum.photos/seed/ga004/800/600', 'f', 't', '4', 'f', NULL, 'CAD', 'f', '{watercolor,nature,light,autumn}', '312', '28', '0', '0', 't', '2026-03-27 15:08:30.146', '2026-03-27 15:08:30.146') ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery_artworks (id, artist_name, title, description, medium, style, year_created, image_url, is_featured, is_public, display_order, is_for_sale, price, currency, accepts_commissions, tags, view_count, favorite_count, comment_count, share_count, is_approved, created_at, updated_at) VALUES ('ga-005', 'Marcus Webb', 'The Wall Speaks', 'Documentary photography of street murals in LA', 'Photography', 'Realism', '2024', 'https://picsum.photos/seed/ga005/800/600', 't', 't', '5', 't', '350.00', 'CAD', 'f', '{photography,street,mural,la,documentary}', '445', '35', '0', '0', 't', '2026-03-27 15:08:30.146', '2026-03-27 15:08:30.146') ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery_artworks (id, artist_name, title, description, medium, style, year_created, image_url, is_featured, is_public, display_order, is_for_sale, price, currency, accepts_commissions, tags, view_count, favorite_count, comment_count, share_count, is_approved, created_at, updated_at) VALUES ('ga-006', 'Priya Sharma', 'Digital Mandala', 'Generative art piece inspired by traditional mandalas', 'Digital Art', 'Abstract', '2026', 'https://picsum.photos/seed/ga006/800/600', 'f', 't', '6', 't', '275.00', 'CAD', 'f', '{mandala,generative,abstract,pattern}', '156', '12', '0', '0', 't', '2026-03-27 15:08:30.146', '2026-03-27 15:08:30.146') ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery_artworks (id, artist_name, title, description, medium, style, year_created, image_url, is_featured, is_public, display_order, is_for_sale, price, currency, accepts_commissions, tags, view_count, favorite_count, comment_count, share_count, is_approved, created_at, updated_at) VALUES ('ga-007', 'Diego Morales', 'Barrio Colors', 'Oil painting capturing the vibrant colors of street markets', 'Oil Painting', 'Expressionism', '2025', 'https://picsum.photos/seed/ga007/800/600', 'f', 't', '7', 'f', NULL, 'CAD', 'f', '{oil,colorful,market,expressionism}', '278', '22', '0', '0', 't', '2026-03-27 15:08:30.146', '2026-03-27 15:08:30.146') ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery_artworks (id, artist_name, title, description, medium, style, year_created, image_url, is_featured, is_public, display_order, is_for_sale, price, currency, accepts_commissions, tags, view_count, favorite_count, comment_count, share_count, is_approved, created_at, updated_at) VALUES ('ga-008', 'Aisha Okonkwo', 'Rhythm & Blues', 'Acrylic on canvas exploring music and movement', 'Acrylic', 'Contemporary', '2024', 'https://picsum.photos/seed/ga008/800/600', 'f', 't', '8', 't', '950.00', 'CAD', 'f', '{acrylic,music,movement,contemporary}', '198', '16', '0', '0', 't', '2026-03-27 15:08:30.146', '2026-03-27 15:08:30.146') ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery_artworks (id, artist_name, title, description, medium, style, year_created, image_url, is_featured, is_public, display_order, is_for_sale, price, currency, accepts_commissions, tags, view_count, favorite_count, comment_count, share_count, is_approved, created_at, updated_at) VALUES ('ga-009', 'Tommy Chen', 'Ink Shadows', 'Traditional Chinese ink wash with modern twist', 'Ink', 'Minimalist', '2025', 'https://picsum.photos/seed/ga009/800/600', 'f', 't', '9', 't', '600.00', 'CAD', 'f', '{ink,minimalist,chinese,traditional}', '167', '14', '0', '0', 't', '2026-03-27 15:08:30.146', '2026-03-27 15:08:30.146') ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery_artworks (id, artist_name, title, description, medium, style, year_created, image_url, is_featured, is_public, display_order, is_for_sale, price, currency, accepts_commissions, tags, view_count, favorite_count, comment_count, share_count, is_approved, created_at, updated_at) VALUES ('ga-010', 'Sofia Restrepo', 'Street Voices Mural', 'Large scale street art documenting community stories', 'Street Art', 'Pop Art', '2026', 'https://picsum.photos/seed/ga010/800/600', 't', 't', '10', 'f', NULL, 'CAD', 'f', '{street-art,mural,community,pop-art,voices}', '890', '67', '0', '0', 't', '2026-03-27 15:08:30.146', '2026-03-27 15:08:30.146') ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery_artworks (id, artist_name, title, description, medium, style, year_created, image_url, is_featured, is_public, display_order, is_for_sale, price, currency, accepts_commissions, tags, view_count, favorite_count, comment_count, share_count, is_approved, created_at, updated_at) VALUES ('ga-011', 'Alex Rivera', 'Charcoal Portrait', 'Raw charcoal portrait capturing human emotion', 'Charcoal', 'Realism', '2025', 'https://picsum.photos/seed/ga011/800/600', 'f', 't', '11', 't', '400.00', 'CAD', 'f', '{charcoal,portrait,realism,emotion}', '145', '11', '0', '0', 't', '2026-03-27 15:08:30.146', '2026-03-27 15:08:30.146') ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery_artworks (id, artist_name, title, description, medium, style, year_created, image_url, is_featured, is_public, display_order, is_for_sale, price, currency, accepts_commissions, tags, view_count, favorite_count, comment_count, share_count, is_approved, created_at, updated_at) VALUES ('ga-012', 'Nina Petrova', 'Watercolor City', 'Loose watercolor cityscape at golden hour', 'Watercolor', 'Impressionism', '2024', 'https://picsum.photos/seed/ga012/800/600', 'f', 't', '12', 't', '525.00', 'CAD', 'f', '{watercolor,cityscape,golden-hour,impressionism}', '234', '19', '0', '0', 't', '2026-03-27 15:08:30.146', '2026-03-27 15:08:30.146') ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery_artworks (id, artist_name, title, description, medium, style, year_created, image_url, is_featured, is_public, display_order, is_for_sale, price, currency, accepts_commissions, tags, view_count, favorite_count, comment_count, share_count, is_approved, created_at, updated_at) VALUES ('ga-013', 'Kwame Asante', 'Digital Heritage', 'Afrofuturist digital collage blending past and future', 'Digital Art', 'Cyberpunk', '2026', 'https://picsum.photos/seed/ga013/800/600', 'f', 't', '13', 't', '700.00', 'CAD', 'f', '{afrofuturist,digital,collage,heritage}', '312', '25', '0', '0', 't', '2026-03-27 15:08:30.146', '2026-03-27 15:08:30.146') ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery_artworks (id, artist_name, title, description, medium, style, year_created, image_url, is_featured, is_public, display_order, is_for_sale, price, currency, accepts_commissions, tags, view_count, favorite_count, comment_count, share_count, is_approved, created_at, updated_at) VALUES ('ga-014', 'Liam OSullivan', 'Mixed Memories', 'Mixed media assemblage using found objects', 'Mixed Media', 'Contemporary', '2025', 'https://picsum.photos/seed/ga014/800/600', 'f', 't', '14', 'f', NULL, 'CAD', 'f', '{mixed-media,assemblage,found-objects,memory}', '178', '13', '0', '0', 't', '2026-03-27 15:08:30.146', '2026-03-27 15:08:30.146') ON CONFLICT (id) DO NOTHING;
INSERT INTO gallery_artworks (id, artist_name, title, description, medium, style, year_created, image_url, is_featured, is_public, display_order, is_for_sale, price, currency, accepts_commissions, tags, view_count, favorite_count, comment_count, share_count, is_approved, created_at, updated_at) VALUES ('ga-015', 'Rosa Gutierrez', 'Photography of Silence', 'Black and white photography exploring urban solitude', 'Photography', 'Minimalist', '2024', 'https://picsum.photos/seed/ga015/800/600', 'f', 't', '15', 't', '300.00', 'CAD', 'f', '{photography,black-white,urban,solitude,minimalist}', '267', '21', '0', '0', 't', '2026-03-27 15:08:30.146', '2026-03-27 15:08:30.146') ON CONFLICT (id) DO NOTHING;

COMMIT;
