[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:xvfb]
command=/usr/bin/Xvfb :99 -screen 0 1280x900x24 -ac
autorestart=true
priority=10

[program:x11vnc]
command=/usr/bin/x11vnc -display :99 -forever -nopw -shared -rfbport 5900 -xkb
autorestart=true
priority=20
environment=DISPLAY=":99"

[program:websockify]
command=/usr/bin/websockify --web=/usr/share/novnc/ 6080 localhost:5900
autorestart=true
priority=30

[program:gnucash]
command=/usr/bin/gnucash
autorestart=true
priority=40
environment=DISPLAY=":99",HOME="/home/gnucash",DBUS_SESSION_BUS_ADDRESS="autolaunch:"
startsecs=3
startretries=5
